// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_ArrayEX_H
#define WINRT_ArrayEX_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.210806.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.210806.1"
#include "winrt/impl/Windows.UI.Composition.2.h"
#include "winrt/impl/Windows.UI.Xaml.2.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.2.h"
#include "winrt/impl/ArrayEX.2.h"
namespace winrt::impl
{
    template <typename D> WINRT_IMPL_AUTO(int32_t) consume_ArrayEX_Imain<D>::MyProperty() const
    {
        int32_t value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::ArrayEX::Imain)->get_MyProperty(&value));
        return value;
    }
    template <typename D> WINRT_IMPL_AUTO(void) consume_ArrayEX_Imain<D>::MyProperty(int32_t value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::ArrayEX::Imain)->put_MyProperty(value));
    }
    template <typename D>
    struct produce<D, winrt::ArrayEX::Imain> : produce_base<D, winrt::ArrayEX::Imain>
    {
        int32_t __stdcall get_MyProperty(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_MyProperty(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::ArrayEX
{
    inline main::main() :
        main(impl::call_factory_cast<main(*)(winrt::Windows::Foundation::IActivationFactory const&), main>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<main>(); }))
    {
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::ArrayEX::Imain> : winrt::impl::hash_base {};
    template<> struct hash<winrt::ArrayEX::main> : winrt::impl::hash_base {};
#endif
}
#endif
