// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_ArrayEX_1_H
#define WINRT_ArrayEX_1_H
#include "winrt/impl/ArrayEX.0.h"
WINRT_EXPORT namespace winrt::ArrayEX
{
    struct __declspec(empty_bases) Imain :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<Imain>
    {
        Imain(std::nullptr_t = nullptr) noexcept {}
        Imain(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
