-- 제목이 반지의 제왕(The Lord Of The Rings)인 비디오 테이프의 장르를 검색하라. 
SELECT GENRE
FROM VIDEO
WHERE TITLE = 'The Lord Of The Rings';

-- 예약된 비디오 테이프의 ID 를 검색하라. 
SELECT DISTINCT(VIDEO_ID)
FROM RESERVED
ORDER BY VIDEO_ID ASC; -- 정렬

-- 예약되지 않은 비디오 테이프의 ID 를 검색하라. 
SELECT DISTINCT(V.VIDEO_ID)
FROM VIDEO V
WHERE V.VIDEO_ID NOT IN (
    SELECT R.VIDEO_ID
    FROM RESERVED R
);

-- 예약된 모든 비디오 데이프의 제목을 검색하라.
SELECT V.TITLE
FROM VIDEO V
WHERE V.VIDEO_ID IN (
    SELECT DISTINCT(R. VIDEO_ID)
    FROM RESERVED R
);

-- 비디오 테이프를 예약한 고객의 이름을 검색하라. 
SELECT NAME
FROM CUSTOMER C, RESERVED R
WHERE R.CUSTOMER_ID IN C.CUSTOMER_ID;

-- 장르가 액션인 비디오 테이프를 예약한 고객의 주소를 검색하라. 
SELECT ADDRESS
FROM CUSTOMER C, RESERVED R, VIDEO V
WHERE UPPER(GENRE) = 'ACTION' AND V.VIDEO_ID = R.VIDEO_ID AND R.CUSTOMER_ID IN C.CUSTOMER_ID;

-- 장르가 다큐멘터리인 비디오 데이프를 모두 예약한 고객의 이름을 검색하라. (RACHEL, KIM)
SELECT NAME
FROM CUSTOMER C
WHERE NOT EXISTS (
    (SELECT VIDEO_ID
    FROM VIDEO
    WHERE UPPER(GENRE) ='DOCUMENTARY')
    MINUS
    (SELECT VIDEO_ID
    FROM RESERVED
    WHERE CUSTOMER_ID = C.CUSTOMER_ID)
);