-- 장르가 다큐멘터리인 비디오 데이프를 모두 예약한 고객의 이름을 검색하라.
SELECT NAME
FROM CUSTOMER C
WHERE NOT EXISTS (
    (SELECT VIDEO_ID
    FROM VIDEO
    WHERE UPPER(GENRE) ='DOCUMENTARY')
    MINUS
    (SELECT VIDEO_ID
    FROM RESERVED
    WHERE CUSTOMER_ID = C.CUSTOMER_ID)
);