--질의 9: 부서에 속한 사원들의 평균 급여가 가장 많은 부서의 이름과 평균 급여를 검색하라. 
SELECT DEPTNAME, AVG(SALARY)
FROM EMPLOYEE, DEPARTMENT
WHERE DEPTNO = DNO
GROUP BY DEPTNAME
HAVING AVG(SALARY) = (SELECT MAX(AVG_SALARY) 
    FROM (SELECT AVG(SALARY) AS AVG_SALARY
    FROM EMPLOYEE
    GROUP BY DNO)
);