--질의 8: 사원이 한 명 이상 속한 부서에 대해서 평균 급여를 검색하라. 
SELECT DEPTNAME, AVG(SALARY)
FROM EMPLOYEE
JOIN DEPARTMENT ON DNO = DEPTNO
WHERE DNO IN (SELECT DNO
FROM EMPLOYEE
GROUP BY DNO
HAVING COUNT(*) > 1)
GROUP BY DEPTNAME;