--질의 19: 자신이 속한 부서의 평균 급여보다 많이 받는 사원의 이름, 부서번호, 급여를 검색하라.
SELECT DISTINCT E1.EMPNAME, E1.DNO, E1.SALARY
FROM EMPLOYEE E1, EMPLOYEE E2 
WHERE E1.DNO = E2.DNO
AND E1.SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE WHERE DNO = E1.DNO);