CREATE TABLE CUSTOMER (
    CUSTOMER_ID int not null,
    NAME varchar(10),
    ADDRESS char(20),
    PHONE char(13),
    PRIMARY KEY(CUSTOMER_ID)
);

CREATE TABLE VIDEO (
    VIDEO_ID int not null,
    TITLE varchar(100),
    GENRE varchar(100),
    PRIMARY KEY(VIDEO_ID)
);

CREATE TABLE RESERVED (
    CUSTOMER_ID int not null,
    VIDEO_ID int not null,
    "DATE" DATE,
    PRIMARY KEY(CUSTOMER_ID, VIDEO_ID),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY(VIDEO_ID) REFERENCES VIDEO(VIDEO_ID)
);